name: train-hyperparameter-tune-deploy-with-pytorch
dependencies:
- pip:
  - azureml-sdk
  - azureml-widgets
  - pillow==5.4.1
  - matplotlib
  - numpy==1.19.3
  - pytorch==1.8.1
  - torchvision==0.9.1
