name: train-explain-model-on-amlcompute-and-deploy
dependencies:
- pip:
  - azureml-sdk
  - azureml-interpret
  - flask
  - flask-cors
  - gevent>=1.3.6
  - jinja2
  - ipython
  - matplotlib
  - azureml-dataset-runtime
  - azureml-core
  - ipywidgets
  - raiwidgets~=0.17.0
  - itsdangerous==2.0.1
  - markupsafe<2.1.0
  - raiutils
