name: train-explain-model-on-amlcompute-and-deploy
dependencies:
- pip:
  - azureml-sdk
  - interpret
  - azureml-interpret
  - azureml-contrib-interpret
  - sklearn-pandas
  - azureml-dataprep
  - azureml-core
  - ipywidgets
