name: train-explain-model-locally-and-deploy
dependencies:
- pip:
  - azureml-sdk
  - azureml-interpret
  - flask
  - flask-cors
  - gevent>=1.3.6
  - jinja2
  - ipython
  - matplotlib
  - ipywidgets
  - raiwidgets~=0.18.1
  - packaging>=20.9
  - itsdangerous==2.0.1
  - markupsafe<2.1.0
