name: train-explain-model-on-amlcompute-and-deploy
dependencies:
- pip:
  - azureml-sdk
  - azureml-interpret
  - flask
  - flask-cors
  - gevent>=1.3.6
  - ipython
  - matplotlib
  - azureml-dataset-runtime
  - azureml-core
  - ipywidgets
  - raiwidgets~=0.23.0
  - itsdangerous==2.0.1
  - markupsafe<2.1.0
  - scipy>=1.5.3
  - protobuf==3.20.0
  - jinja2==3.0.3
