name: train-explain-model-locally-and-deploy
dependencies:
- pip:
  - azureml-sdk
  - azureml-interpret
  - flask
  - flask-cors
  - gevent>=1.3.6
  - jinja2
  - ipython
  - matplotlib
  - ipywidgets
