name: train-hyperparameter-tune-deploy-with-tensorflow
dependencies:
- numpy
- matplotlib
- pip:
  - azureml-sdk
  - azureml-widgets
  - pandas
  - keras
  - tensorflow==2.0.0
  - matplotlib
  - fuse
