# Copyright (c) Microsoft. All rights reserved.
#  Licensed under the MIT license.
name: tutorial
channels:
  - defaults
dependencies:
  - numpy>=1.14.3
  - pandas>=1.0.0
  - scikit-learn=0.19.1
  - pip
  - pip:
    - mlflow
    - azureml-mlflow