name: train-explain-model-gpu-tree-explainer
dependencies:
- py-xgboost==1.3.3
- pip:
  - azureml-sdk
  - azureml-interpret
  - flask
  - flask-cors
  - gevent>=1.3.6
  - jinja2
  - ipython
  - matplotlib
  - ipywidgets
  - raiwidgets~=0.21.0
  - itsdangerous==2.0.1
  - markupsafe<2.1.0
  - scipy>=1.5.3
  - protobuf==3.20.0
