name: train-explain-model-locally-and-deploy
dependencies:
- pip:
  - azureml-sdk
  - azureml-interpret
  - interpret-community[visualization]
  - matplotlib
  - azureml-contrib-interpret
  - sklearn-pandas
  - ipywidgets
